# Generated by Django 2.1.5 on 2019-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20191011_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
