# Generated by Django 2.1.5 on 2019-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20191011_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.IntegerField(),
        ),
    ]
